server:
  port: '${EMAIL_INTEGRATION_SERVER_PORT:-8080}'
  shutdown: graceful
spring:
  application:
    name: '@project.artifactId@'
  cloud:
    stream:
      bindings:
        functionRouter-in-0:
          group: "dwf-email-service"
          destination: "dwf-email-${DIGIWF_ENV}"
        sendMessage-out-0:
          destination: "dwf-connector-${DIGIWF_ENV}"
  mail:
    port: ${MAIL_PORT:1025}
    host: ${MAIL_HOST:localhost}
    username: ${MAIL_USERNAME:digiwf@muenchen.de}
    password: ${MAIL_PASSWORD:test}
    properties:
      mail:
        debug: false
        tls: true
        transport:
          protocol: smtp
        smtp:
          port: ${MAIL_PORT:1025}
          host: ${MAIL_HOST:localhost}
          connectiontimeout: '10000'
          timeout: '10000'
          auth: true
          ssl:
            trust: '*'
            checkserveridentity: false
          socketFactory:
            fallback: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus, livenessstate, readinessstate
io:
  muenchendigital:
    digiwf:
      mail:
        fromAddress: ${MAIL_USERNAME:itm.digiwf@muenchen.de}
        metrics:
          totalMailCounterName: "digiwf.email.integration.send_mail.total"
          failureCounterName: "digiwf.email.integration.send_mail.failure"
      message:
        incidentDestination: "dwf-connector-incident-${DIGIWF_ENV}"
        bpmnErrorDestination: "dwf-connector-bpmnerror-${DIGIWF_ENV}"
        correlateMessageDestination: "dwf-connector-${DIGIWF_ENV}"
        deadLetterQueueDestination: "dwf-connector-incident-${DIGIWF_ENV}"
