info:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'

camunda:
  bpm:
    authorization:
      enabled: true
    job-execution:
      enabled: false
    database:
      schema-update: false

management:
  server:
    port: '${ENGINE_REST_SERVER_PORT:8080}'
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health, info, prometheus, livenessstate, readinessstate'
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  health:
    ldap:
      enabled: false

server:
  port: '${ENGINE_REST_SERVER_PORT:8080}'
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
  shutdown: graceful

spring:
  application:
    name: ${info.application.name}
  datasource:
    url: '${ENGINE_DATASOURCE_URL:jdbc:h2:file:~/backenddb;DB_CLOSE_ON_EXIT=FALSE}'
    username: '${ENGINE_DATASOURCE_USER:sa}'
    password: '${ENGINE_DATASOURCE_PASSWORD:}'
  ldap:
    urls: '${LDAP_URL:}'
    username: '${LDAP_USERNAME:}'
    password: '${LDAP_PASSWORD:}'

digiwf:
  security:
    client-id: ${SSO_ENGINE_CLIENT_ID}
    client-secret: ${SSO_ENGINE_CLIENT_SECRET}
  ldap:
    group-base: '${LDAP_GROUP_BASE:}'
    user-base: '${LDAP_USER_BASE:}'
