info:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
    stage:
      color: ${STAGE_COLOR:#FFCC00}
      displayName: ${STAGE_DISPLAY_NAME:${DIGIWF_ENV}}
spring:
  application:
    name: ${info.application.name}
  main:
    web-application-type: reactive
  jackson:
    serialization:
      indent-output: on
  session:
    timeout: 1800  # in seconds; Goal: same lifetime as SSO Session, actual: 30 minutes
  zipkin:
    enabled: false
    sleuth:
      reactor:
        instrumentation-type: decorate_on_each  # https://github.com/spring-cloud/spring-cloud-gateway/pull/2106
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SSO_ISSUER_URL:sso.muenchen.de}
      client:
        provider:
          keycloak:
            issuer-uri: ${SSO_ISSUER_URL}
        registration:
          keycloak:
            client-id: ${SSO_ENGINE_CLIENT_ID}
            client-secret: ${SSO_ENGINE_CLIENT_SECRET}
            scope: email, profile, openid  # needed for userInfo endpoint
            provider: keycloak
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/public/**]':
            allowedOriginPatterns: ${ALLOWED_ORIGINS_PUBLIC}
          '[/clients/**]':
            allowedOriginPatterns: ${ALLOWED_ORIGINS_CLIENTS}
            allowedHeaders: "*"
            allowCredentials: true

digiwf:
  security:
    csrf-whitelisted:
      - "/optimize/**"

server:
  port: ${GATEWAY_SERVER_PORT:8082}
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always
    whitelabel:
      enabled: false
  shutdown: graceful

management:
  endpoints:
    enabled-by-default: false
    web:
      cors:
        allowedOrigins:
          - "http://localhost:8081"
          - "http://127.0.0.1:8081"
          - "http://localhost:8083" # for cgi notebooks necessary
          - "http://127.0.0.1:8083" # for cgi notebooks necessary
          - "http://keycloak:8083" # for cgi notebooks necessary
          - "http://127.0.0.1:8084"
          - "http://localhost:8084"
          - "http://127.0.0.1:8085"
          - "http://localhost:8085"
        allowedMethods: "*"
        allowedHeaders: "*"
        allowCredentials: on
        maxAge: 3600
      exposure:
        include: health, info, prometheus, livenessstate, readinessstate
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      enabled: on
      probes:
        enabled: true
    info:
      enabled: on
    prometheus:
      enabled: on
  info:
    env:
      enabled: true

config:
  map5xxto400: true
