name: Contribution Bot

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Get-Team'
        if: github.event.issue.author_association != 'MEMBER'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          debug: true
          script: |
            const { repo, owner } = context.repo;
            const issue_number = context.issue.number;
            const maintainers = await github.rest.teams.listMembersInOrg({
                org: owner,
                team_slug: 'digiwf_maintainer'
            });
            return maintainers.data.map(u => u.login)
      - name: 'Assign Issue'
        if: github.event.issue.author_association != 'MEMBER'
        uses: actions/github-script@v7
        with:
          debug: true
          script: |
            const { repo, owner } = context.repo;
            const issue_number = context.issue.number;
            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number,
              assignees: `${{steps.set-result.outputs.result}}`,
            });
            await github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body: '👋 Thanks for reporting! The maintainers have been notified and will get back to you.'
            });
