name: Contribution Bot

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign issue'
        if: github.event.issue.author_association != 'MEMBER'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          debug: true
          script: |
            const { repo, owner } = context.repo;
            const issue_number = context.issue.number;
            const teamMembers =  await github.rest.teams.listMembersInOrg({
                org: owner,
                team_slug: 'digiwf_maintainer'
            })
            await github.rest.issues.addAssignees({
              owner: owner,
              owner: repo,
              issue_number: issue_number,
              assignees: teamMembers.data.map(u => u.login),
            });
            await github.rest.issues.createComment({
              issue_number: issue_number,
              owner: owner,
              repo: repo,
              body: '👋 Thanks for reporting! The maintainers have been notified and will get back to you.'
            });
